### ISSUE TITLE
NewType variants seems superfluous

### ISSUE THREAD

**Issue by Ploppz** [facebookincubator/serde-reflection#10]
In `VariantFormat` and `ContainerFormat`, there is a separation between `NewTypeStruct(Box<Format>)` and `TupleStruct(Vec<Format>)`. As far as I can see, in most cases the distinction is not really important, and it serves to increase the complexity of code dealing with these format structs.
For example I'm creating a proc macro right now to derive a trait that returns the `Format` of a type (because `serde-reflection` is not _yet_ able to always find the right format by just relying on `serde` - my effort is meant as complementary, and relies on the data structures of `serde-reflection`), ... and `syn`'s model does not make the same distinction: https://docs.rs/syn/1.0.23/syn/enum.Fields.html.

I would suggest removing `NewTypeStruct` and let any users of the library instead just check the length of the Vec in `TupleStruct` to see whether it's a newtype.

**Comment by matbd** [comment]
Good question. I actually thought about this quite a bit.
* The [documentation of Serde](https://serde.rs/data-model.html) is very clear about distinguishing the different flavors of structs and variants. So there's that.
* This distinction has no consequence for bincode but other encodings may rely on it. For instance, JSON [does](https://serde.rs/impl-serialize.html#serializing-a-struct). In theory, this means that Serde users may decide to implement Serialize for a NewTypeStruct by hand and serialize it as a Struct with one field in order to achieve a different serialization.
* For binary formats like bincode (arguably a more compelling use case for Serde-reflection than self-describing formats), I found that the distinction between a NewTypeStruct and a Struct with one field could also prove useful in the future to control code generation. Concretely, a NewTypeStruct could translate more naturally as a type alias in many languages (e.g. a `using` statement in C++11). If someone does not want this, then they can change the Serde format to be a struct with one field.

**Comment by Ploppz** [comment]
Good points. I didn't realize that it's also like that in the Serde model.
